#!/bin/sh

set -e

export PATH=/usr/bin

while getopts l:t: opt; do
  case $opt in
    l) LOWER="$OPTARG" ;;
    t) TMP="$OPTARG" ;;
    *) exit 1 ;;
  esac
done

shift $((OPTIND - 1))

helper_mount() {
  # ensure directory permissions match
  [ "$(stat -c %a "$LOWER")" = "$(stat -c %a "$TMP")" ]
  [ "$(stat -c %u "$LOWER")" = "$(stat -c %u "$TMP")" ]
  [ "$(stat -c %g "$LOWER")" = "$(stat -c %g "$TMP")" ]

  mount -t overlay overlay -o nosuid,nodev,noatime "$TMP/overlay" \
    -o lowerdir="$LOWER" \
    -o upperdir="$TMP/upper" \
    -o workdir="$TMP/work"

  touch -r "$LOWER" "$TMP/overlay"
}

helper_unmount() {
  # ensure mount is overlay
  [ "$(stat -f -c %T "$TMP/overlay")" = overlayfs ]

  # ensure directory is work directory
  [ "$(stat -c %a "$TMP/work/work")" = 0 ]

  umount "$TMP/overlay"

  rm -rf "$TMP/work/work"
}

case $1 in
  mount)
    helper_mount
    ;;

  unmount)
    helper_unmount
    ;;
esac
