#!/bin/sh

HELP=$(command -v firefox-overlay-helper)

USER=$(id -un)
HOME=$(getent passwd "$USER" | cut -d : -f 6)

env_check() {
  if [ ! -d "$HOME/.mozilla/firefox" ] && [ ! -L "$HOME/.mozilla/firefox" ]; then
    die 1 "directory '$HOME/.mozilla/firefox': not found"
  fi

  if [ -z "$XDG_RUNTIME_DIR" ]; then
    die 1 "XDG_RUNTIME_DIR not set"
  fi

  if [ ! -d "$XDG_RUNTIME_DIR" ]; then
    die 1 "directory '$XDG_RUNTIME_DIR': not found"
  fi
}

helper_check() {
  if [ -z "$HELP" ]; then
    die 1 "firefox-overlay-helper not found"
  fi

  # support for both sudo and doas; doas takes precedence
  if command -v doas > /dev/null 2>&1; then
    if ! doas -n "$HELP"; then
      die 1 "cannot run 'doas' without password"
    fi
  else
    if ! sudo -n "$HELP"; then
      die 1 "cannot run 'sudo' without password"
    fi
  fi
}

run_as_root() {
  # support for both sudo and doas; doas takes precedence
  if command -v doas > /dev/null 2>&1; then
    doas -n "$@"
  else
    sudo -n "$@"
  fi
}

overlay_mount() {
  if mountpoint -q "$XDG_RUNTIME_DIR/firefox-overlay/overlay"; then
    die 1 "overlay already mounted"
  fi

  if [ -L "$HOME/.mozilla/firefox" ] && [ -d "$HOME/.mozilla/firefox-lower" ]; then
    rm -f "$HOME/.mozilla/firefox"
  elif [ -d "$HOME/.mozilla/firefox" ] && [ ! -e "$HOME/.mozilla/firefox-lower" ]; then
    mv -f "$HOME/.mozilla/firefox" "$HOME/.mozilla/firefox-lower"
  else
    die 1 "directory '$HOME/.mozilla/firefox-lower': not created"
  fi

  ln -s firefox-lower "$HOME/.mozilla/firefox"

  install -d \
    -m "$(stat -c %a "$HOME/.mozilla/firefox-lower")" \
    -o "$(stat -c %u "$HOME/.mozilla/firefox-lower")" \
    -g "$(stat -c %g "$HOME/.mozilla/firefox-lower")" \
    "$XDG_RUNTIME_DIR/firefox-overlay" \
    "$XDG_RUNTIME_DIR/firefox-overlay/overlay" \
    "$XDG_RUNTIME_DIR/firefox-overlay/upper" \
    "$XDG_RUNTIME_DIR/firefox-overlay/work"

  run_as_root "$HELP" -l "$HOME/.mozilla/firefox-lower" -t "$XDG_RUNTIME_DIR/firefox-overlay" mount

  rm -f "$HOME/.mozilla/firefox"

  ln -s "$XDG_RUNTIME_DIR/firefox-overlay/overlay" "$HOME/.mozilla/firefox"
}

overlay_unmount() {
  if mountpoint -q "$XDG_RUNTIME_DIR/firefox-overlay/overlay"; then
    run_as_root "$HELP" -t "$XDG_RUNTIME_DIR/firefox-overlay" unmount
  fi

  if [ -L "$HOME/.mozilla/firefox" ] && [ -d "$HOME/.mozilla/firefox-lower" ]; then
    rm -f "$HOME/.mozilla/firefox"

    mv -f "$HOME/.mozilla/firefox-lower" "$HOME/.mozilla/firefox"
  fi

  if [ -d "$XDG_RUNTIME_DIR/firefox-overlay" ]; then
    rm -rf "$XDG_RUNTIME_DIR/firefox-overlay/upper"

    rmdir \
      "$XDG_RUNTIME_DIR/firefox-overlay/overlay" \
      "$XDG_RUNTIME_DIR/firefox-overlay/work" \
      "$XDG_RUNTIME_DIR/firefox-overlay"
  fi
}

overlay_flush() {
  if ! mountpoint -q "$XDG_RUNTIME_DIR/firefox-overlay/overlay"; then
    die 1 "overlay not mounted"
  fi

  if [ ! -L "$HOME/.mozilla/firefox" ] || [ ! -d "$HOME/.mozilla/firefox-lower" ]; then
    die 1 "discrepancy detected"
  fi

  exec rsync -a --delete-after --inplace --no-whole-file \
    "$XDG_RUNTIME_DIR/firefox-overlay/overlay/" "$HOME/.mozilla/firefox-lower/"
}

overlay_check() {
  printf "%b" "${YLW}firefox${RST} (ssd) - "
  du -sh "$HOME/.mozilla/firefox-lower" | awk '{print $1}'

  printf "%b" "${GRN}overlay${RST} (mem) - "
  du -sh "$XDG_RUNTIME_DIR/firefox-overlay/upper" | awk '{print $1}'
}

die() {
  printf "firefox-overlay: %s\n" "$2" 1>&2

  exit "$1"
}

RST='\033[0;00m'
GRN='\033[0;32m'
YLW='\033[0;33m'

usage() {
  printf "%b\n" "${YLW}USAGE${RST}:"
  printf "%s\n" "    firefox-overlay [SUBCOMMAND]"
  printf "\n"
  printf "%b\n" "${YLW}SUBCOMMANDS${RST}:"
  printf "%b\n" "    ${GRN}m${RST}, ${GRN}mount${RST}      Mount overlay"
  printf "%b\n" "    ${GRN}u${RST}, ${GRN}unmount${RST}    Unmount overlay"
  printf "%b\n" "    ${GRN}f${RST}, ${GRN}flush${RST}      Flush overlay to disk"
  printf "%b\n" "    ${GRN}c${RST}, ${GRN}check${RST}      Check overlay status"
}

set -e

case $1 in
  m | mount)
    env_check
    helper_check
    overlay_mount
    ;;

  u | unmount)
    env_check
    helper_check
    overlay_unmount
    ;;

  f | flush)
    env_check
    overlay_flush
    ;;

  c | check)
    overlay_check
    ;;

  h | -h | help | --help | "")
    usage
    ;;

  *)
    die 1 "unrecognized command '$1'"
    ;;
esac
