#!/bin/sh

set -e

TMP="${XDG_RUNTIME_DIR:-/tmp}/.cache"

if [ -z "$HOME" ]; then
  HOME=$(getent passwd "$(id -un)" | cut -d : -f 6)

  export HOME
fi

if [ -z "$XDG_CACHE_HOME" ]; then
  XDG_CACHE_HOME="$HOME/.cache"

  export XDG_CACHE_HOME
fi

if [ -L "$XDG_CACHE_HOME" ]; then
  rm -f "$XDG_CACHE_HOME"
fi

if [ -d "$TMP" ]; then
  rm -rf "$TMP"
fi
