#!/bin/sh

set -e

TMP="${XDG_RUNTIME_DIR:-/tmp}/.cache"

[ -z "$HOME" ] && HOME=$(getent passwd "$(id -un)" | cut -d : -f 6)

XDG_CACHE_HOME="$HOME/.cache"

[ -L "$XDG_CACHE_HOME" ] && unlink "$XDG_CACHE_HOME"

[ -e "$TMP" ] && rm -rf "$TMP"
