#!/bin/sh

set -e

[ -n "$HOME" ]
[ -n "$XDG_RUNTIME_DIR" ]

XDG_CACHE_HOME="$HOME/.cache"
TMP="$XDG_RUNTIME_DIR/.cache"

[ -d "$TMP" ] && rm -rf "$TMP"
[ -d "$XDG_CACHE_HOME" ] && rm -rf "$XDG_CACHE_HOME"

install -d -m 0700 "$TMP"
ln -fs "$TMP" "$XDG_CACHE_HOME"

exec chpst -b cache pause
