#!/bin/sh

set -e

TMP="${XDG_RUNTIME_DIR:-/tmp}/.cache"

[ -z "$HOME" ] && HOME=$(getent passwd "$(id -un)" | cut -d : -f 6)

XDG_CACHE_HOME="$HOME/.cache"

[ -L "$XDG_CACHE_HOME" ] && unlink "$XDG_CACHE_HOME" # ungraceful shutdown
[ -e "$XDG_CACHE_HOME" ] && rm -rf "$XDG_CACHE_HOME"

install -d -m 700 "$TMP"

ln -s "$TMP" "$XDG_CACHE_HOME"

exec chpst -b cache pause
