#!/bin/sh

set -e

TMP="${XDG_RUNTIME_DIR:-/tmp}/firefox-overlay"

[ -z "$HOME" ] && HOME=$(getent passwd "$(id -un)" | cut -d : -f 6)

LOWER="$HOME/.mozilla/firefox"

env_check() {
  if [ ! -x "@HELPER@" ]; then
    die "executable '@HELPER@': not found"
  fi

  if [ ! -d "$LOWER" ] && [ ! -L "$LOWER" ]; then
    die "directory '$LOWER': not found"
  fi
}

overlay_helper() {
  if command -v doas > /dev/null; then
    doas -n "@HELPER@" "$@" || return 1
  else
    sudo -n "@HELPER@" "$@" || return 1
  fi
}

overlay_mount() {
  if [ -e "$TMP" ]; then
    die "directory '$TMP': already exists"
  fi

  # ungraceful shutdown
  if [ -L "$LOWER" ] && [ -d "${LOWER}-lower" ]; then
    unlink "$LOWER"

  # default state
  elif [ -d "$LOWER" ] && [ ! -e "${LOWER}-lower" ]; then
    mv -Tn "$LOWER" "${LOWER}-lower"

  else
    die "directory '${LOWER}-lower': not found"
  fi

  ln -s firefox-lower "$LOWER"

  install -d -m 700 "$TMP/overlay" "$TMP/upper" "$TMP/work"

  if ! overlay_helper mount "$TMP" "${LOWER}-lower"; then
    overlay_unmount

    die "failed to mount overlay"
  fi

  unlink "$LOWER"

  ln -s "$TMP/overlay" "$LOWER"
}

overlay_unmount() {
  if [ -L "$LOWER" ] && [ -d "${LOWER}-lower" ]; then
    unlink "$LOWER"

    mv -Tn "${LOWER}-lower" "$LOWER"
  fi

  if [ -e "$TMP" ]; then
    if [ -e "$TMP/overlay" ]; then
      if ! overlay_helper unmount "$TMP" && ! rmdir "$TMP/overlay"; then
        die "failed to unmount overlay"
      fi
    fi

    rm -rf "$TMP"
  fi
}

overlay_flush() {
  if [ ! -f "$TMP/overlay/profiles.ini" ]; then
    die "overlay not mounted"
  fi

  if [ ! -L "$LOWER" ] || [ ! -d "${LOWER}-lower" ]; then
    die "overlay not mounted"
  fi

  if ! rsync -aAX --delete-after --inplace --no-whole-file "$TMP/overlay"/ "${LOWER}-lower"/; then
    die "failed to flush overlay"
  fi
}

overlay_check() {
  if [ ! -e "$TMP" ]; then
    die "overlay not mounted"
  fi

  printf %b "${YLW}firefox${RST} (ssd) - "
  du -sh "${LOWER}-lower" | awk '{print $1}'

  printf %b "${GRN}overlay${RST} (mem) - "
  du -sh "$TMP/upper" | awk '{print $1}'
}

die() {
  printf "firefox-overlay: %s\n" "$*" >&2
  exit 1
}

RST='\033[0;00m'
GRN='\033[0;32m'
YLW='\033[0;33m'

usage() {
  printf "%b\n" "${YLW}USAGE${RST}:"
  printf "%s\n" "    firefox-overlay [SUBCOMMAND]"
  printf "\n"
  printf "%b\n" "${YLW}SUBCOMMANDS${RST}:"
  printf "%b\n" "    ${GRN}m${RST}, ${GRN}mount${RST}      Mount overlay"
  printf "%b\n" "    ${GRN}u${RST}, ${GRN}unmount${RST}    Unmount overlay"
  printf "%b\n" "    ${GRN}f${RST}, ${GRN}flush${RST}      Flush overlay to disk"
  printf "%b\n" "    ${GRN}c${RST}, ${GRN}check${RST}      Check overlay status"
}

case $1 in
  m | mount)
    env_check
    overlay_mount
    ;;

  u | unmount)
    env_check
    overlay_unmount
    ;;

  f | flush)
    env_check
    overlay_flush
    ;;

  c | check)
    overlay_check >&2
    ;;

  h | -h | help | --help | "")
    usage >&2
    ;;

  *)
    die "unrecognized command '$1'"
    ;;
esac
