#!/bin/sh

set -e

export PATH=/usr/bin

TMP="$2"
LOWER="$3"

helper_mount() {
  [ -d "$LOWER" ]
  [ -d "$TMP/overlay" ]
  [ -d "$TMP/upper" ]
  [ -d "$TMP/work" ]

  mount -t overlay overlay -o nosuid,nodev,noatime "$TMP/overlay" \
    -o lowerdir="$LOWER" \
    -o upperdir="$TMP/upper" \
    -o workdir="$TMP/work"

  touch -r "$LOWER" "$TMP/overlay"
}

helper_unmount() {
  [ -d "$TMP/overlay" ]
  [ -d "$TMP/work/work" ]

  umount "$TMP/overlay"

  rm -rf "$TMP/work/work"
}

case $1 in
  mount)
    helper_mount
    ;;

  unmount)
    helper_unmount
    ;;

  *)
    printf "firefox-overlay-helper: use 'firefox-overlay' instead\n" >&2
    exit 1
    ;;
esac
