#!/bin/sh

set -e

[ -n "$HOME" ]
[ -n "$XDG_RUNTIME_DIR" ]

TMP="$XDG_RUNTIME_DIR/firefox-overlay"

UPPER="$HOME/.mozilla/firefox"
LOWER="$HOME/.mozilla/firefox-lower"

TEST="$TMP/overlay/profiles.ini"

env_check() {
  if [ ! -x "@HELPER@" ]; then
    die "executable '@HELPER@': not found"
  fi

  if [ ! -d "$UPPER" ] && [ ! -L "$UPPER" ]; then
    die "directory '$LOWER': not found"
  fi
}

overlay_helper() {
  if command -v doas > /dev/null; then
    doas -n "@HELPER@" "$@" || return 1
  else
    sudo -n "@HELPER@" "$@" || return 1
  fi
}

overlay_mount() {
  if [ -e "$TMP" ]; then
    die "directory '$TMP': already exists"
  fi

  # ungraceful shutdown
  if [ -L "$UPPER" ] && [ -d "$LOWER" ]; then
    rm -f "$UPPER"

  # default state
  elif [ -d "$UPPER" ] && [ ! -e "$LOWER" ]; then
    mv -Tn "$UPPER" "$LOWER"

  else
    die "directory '$LOWER': not found"
  fi

  ln -s firefox-lower "$UPPER"

  install -d -m 0700 "$TMP/overlay" "$TMP/upper" "$TMP/work"

  if ! overlay_helper mount "$TMP" "$LOWER"; then
    rm -f "$UPPER"

    mv -T "$LOWER" "$UPPER"

    rmdir "$TMP/overlay" "$TMP/upper" "$TMP/work" "$TMP"

    die "failed to mount overlay"
  fi

  rm -f "$UPPER"

  ln -s "$TMP/overlay" "$UPPER"
}

overlay_unmount() {
  if [ -L "$UPPER" ] && [ -d "$LOWER" ]; then
    rm -f "$UPPER"

    mv -T "$LOWER" "$UPPER"
  fi

  if [ -e "$TMP" ]; then
    if ! overlay_helper unmount "$TMP"; then
      die "failed to unmount overlay"
    fi

    rm -rf "$TMP"
  fi
}

overlay_flush() {
  if [ ! -f "$TEST" ]; then
    die "overlay not mounted"
  fi

  if [ ! -L "$UPPER" ] || [ ! -d "$LOWER" ]; then
    die "overlay not mounted"
  fi

  if ! rsync -aAX --delete-after --inplace --no-whole-file "$TMP/overlay"/ "$LOWER"/; then
    die "failed to flush overlay"
  fi
}

overlay_check() {
  if [ ! -e "$TMP" ]; then
    die "overlay not mounted"
  fi

  printf %b "${YLW}firefox${RST} (ssd) - "
  du -sh "$LOWER" | awk '{print $1}'

  printf %b "${GRN}overlay${RST} (mem) - "
  du -sh "$TMP/upper" | awk '{print $1}'
}

die() {
  printf "firefox-overlay: %s\n" "$*" >&2
  exit 1
}

RST='\033[0;00m'
GRN='\033[0;32m'
YLW='\033[0;33m'

usage() {
  printf "%b\n" "${YLW}USAGE${RST}:"
  printf "%s\n" "    firefox-overlay [SUBCOMMAND]"
  printf "\n"
  printf "%b\n" "${YLW}SUBCOMMANDS${RST}:"
  printf "%b\n" "    ${GRN}m${RST}, ${GRN}mount${RST}      Mount overlay"
  printf "%b\n" "    ${GRN}u${RST}, ${GRN}unmount${RST}    Unmount overlay"
  printf "%b\n" "    ${GRN}f${RST}, ${GRN}flush${RST}      Flush overlay to disk"
  printf "%b\n" "    ${GRN}c${RST}, ${GRN}check${RST}      Check overlay status"
}

case $1 in
  m | mount)
    env_check
    overlay_mount
    ;;

  u | unmount)
    env_check
    overlay_unmount
    ;;

  f | flush)
    env_check
    overlay_flush
    ;;

  c | check)
    overlay_check >&2
    ;;

  *)
    usage >&2
    ;;
esac
