#!/bin/sh

set -e

TMP="${XDG_RUNTIME_DIR:-/tmp}/firefox-overlay"

HOME=$(getent passwd "$(id -un)" | cut -d : -f 6)

export HOME

LOWER="$HOME/.mozilla/firefox"

env_check() {
  if [ ! -x "@HELPER@" ]; then
    die 1 "executable '@HELPER@': not found"
  fi

  if [ ! -e "$LOWER" ]; then
    die 1 "directory '$LOWER': not found"
  fi
}

overlay_helper() {
  # support for both sudo and doas; doas takes precedence
  if [ -x /usr/bin/doas ]; then
    doas -n "@HELPER@" "$@"
  else
    sudo -n "@HELPER@" "$@"
  fi
}

overlay_mount() {
  if [ -e "$TMP" ]; then
    die 1 "directory '$TMP': already exists"
  fi

  # ungraceful shutdown
  if [ -L "$LOWER" ] && [ -d "${LOWER}-lower" ]; then
    rm -f "$LOWER"

  # default state
  elif [ -d "$LOWER" ] && [ ! -e "${LOWER}-lower" ]; then
    mv -f "$LOWER" "${LOWER}-lower"

  else
    die 1 "directory '${LOWER}-lower': not found"
  fi

  ln -s firefox-lower "$LOWER"

  install -d -m 700 "$TMP/overlay" "$TMP/upper" "$TMP/work"

  if ! overlay_helper mount "$TMP" "${LOWER}-lower"; then
    die 1 "failed to mount overlay"
  fi

  rm -f "$LOWER"

  ln -s "$TMP/overlay" "$LOWER"
}

overlay_unmount() {
  if [ -e "$TMP" ]; then
    if [ -e "$TMP/overlay" ]; then
      if ! overlay_helper unmount "$TMP"; then
        die 1 "failed to unmount overlay"
      fi

      rmdir "$TMP/overlay"
    fi

    rm -rf "$TMP"
  fi

  if [ -L "$LOWER" ] && [ -d "${LOWER}-lower" ]; then
    rm -f "$LOWER"

    mv -f "${LOWER}-lower" "$LOWER"
  fi
}

overlay_flush() {
  if [ ! -f "$TMP/overlay/profiles.ini" ]; then
    die 1 "overlay not mounted"
  fi

  if [ ! -L "$LOWER" ] || [ ! -d "${LOWER}-lower" ]; then
    die 1 "overlay not mounted"
  fi

  if ! rsync -aAX --delete-after --inplace --no-whole-file "$TMP/overlay"/ "${LOWER}-lower"/; then
    die 1 "failed to flush overlay"
  fi
}

overlay_check() {
  if [ ! -e "$TMP" ]; then
    die 0 "overlay not mounted"
  fi

  printf %b "${YLW}firefox${RST} (ssd) - "
  du -sh "${LOWER}-lower" | awk '{print $1}'

  printf %b "${GRN}overlay${RST} (mem) - "
  du -sh "$TMP/upper" | awk '{print $1}'
}

die() {
  printf "firefox-overlay: %s\n" "$2" 1>&2

  exit "$1"
}

RST='\033[0;00m'
GRN='\033[0;32m'
YLW='\033[0;33m'

usage() {
  printf "%b\n" "${YLW}USAGE${RST}:"
  printf "%s\n" "    firefox-overlay [SUBCOMMAND]"
  printf "\n"
  printf "%b\n" "${YLW}SUBCOMMANDS${RST}:"
  printf "%b\n" "    ${GRN}m${RST}, ${GRN}mount${RST}      Mount overlay"
  printf "%b\n" "    ${GRN}u${RST}, ${GRN}unmount${RST}    Unmount overlay"
  printf "%b\n" "    ${GRN}f${RST}, ${GRN}flush${RST}      Flush overlay to disk"
  printf "%b\n" "    ${GRN}c${RST}, ${GRN}check${RST}      Check overlay status"
}

case $1 in
  m | mount)
    env_check
    overlay_mount
    ;;

  u | unmount)
    env_check
    overlay_unmount
    ;;

  f | flush)
    env_check
    overlay_flush
    ;;

  c | check)
    overlay_check
    ;;

  h | -h | help | --help | "")
    usage
    ;;

  *)
    die 1 "unrecognized command '$1'"
    ;;
esac
